[package]
name = "async-oneshot"
version = "0.1.0"
authors = ["James Laver <james.laver@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-lite="0.1"
# ping-pong-cell = { git = "https://github.com/irrustible/ping-pong-cell", branch = "main" }
ping-pong-cell = { path = "../ping-pong-cell" }

# [dev-dependencies]
# waker-fn = "1"